// Build 87 / server v0.4.615 — decodes the REAL `twoToOneVerify` payload
// shape (sample.json, generated by gen_sample.js from evv-poc's own
// two-to-one-verify.describe()) with the REAL app structs (extracted from
// APIClient.swift by check.sh), and exercises the local countdown.
import Foundation

var pass = 0, fail = 0
func check(_ label: String, _ ok: Bool, _ extra: String = "") {
    if ok { pass += 1; print("  ✓ \(label)") } else { fail += 1; print("  ✗ \(label) \(extra)") }
}

let sampleURL = URL(fileURLWithPath: CommandLine.arguments[1])
let data = try! Data(contentsOf: sampleURL)
let resp = try! JSONDecoder().decode(ShiftsResponse.self, from: data)

print("[decode] GET /api/me/shifts → twoToOneVerify")
let tto = resp.twoToOneVerify!
check("pending (addressed to me) decodes 1 row", tto.pending.count == 1, "\(tto.pending.count)")
check("mine (my running visits) decodes 2 rows", tto.mine.count == 2, "\(tto.mine.count)")
check("windowSec = 120 default", tto.windowSec == 120)
let p = tto.pending[0]
check("requestId Int / Identifiable id", p.requestId == 7 && p.id == 7)
check("requestedBy + secondStaff names", p.requestedBy.name == "Nick Mudgett" && p.secondStaff.staffId == "S203")
check("individual + service + serviceName", p.individual?.name == "Dustin Sackett" && p.service == "W7068" && p.serviceName == "In-Home & Community Support (2:1)")
check("clockIn is the requester's punch (the time I will be recorded at)", p.clockIn == "2:33 PM")
check("status pending / isPending", p.status == "pending" && p.isPending)
check("expiresAt parses (ISO 8601 with fractional seconds)", p.expiresDate != nil)
// countdown: now = 30 s before expiry → 30
let exp = p.expiresDate!
check("secondsRemaining counts down off expiresAt", p.secondsRemaining(at: exp.addingTimeInterval(-30)) == 30, "\(p.secondsRemaining(at: exp.addingTimeInterval(-30)))")
check("…floors at 0 after expiry", p.secondsRemaining(at: exp.addingTimeInterval(5)) == 0)
let m0 = tto.mine[0], m1 = tto.mine[1]
check("mine[0] expired with secondsLeft 0", m0.status == "expired" && !m0.isPending && m0.secondsLeft == 0)
check("mine[1] confirmed with confirmedVisitId", m1.status == "confirmed" && m1.confirmedVisitId == "V-3000")

print("[decode] tolerance")
let older = """
{"shifts":[],"openShifts":[]}
""".data(using: .utf8)!
let old = try! JSONDecoder().decode(ShiftsResponse.self, from: older)
check("an older server (no twoToOneVerify key) decodes → nil → no banner", old.twoToOneVerify == nil)
let minimal = """
{"pending":[{"requestId":1,"requestedBy":{"staffId":"A","name":"A"},"secondStaff":{"staffId":"B","name":"B"},"status":"pending"}],"mine":[]}
""".data(using: .utf8)!
let mini = try! JSONDecoder().decode(TwoToOneVerifyPayload.self, from: minimal)
check("a minimal row (no individual/clockIn/expiresAt) decodes; countdown falls back to secondsLeft (0)", mini.pending.count == 1 && mini.pending[0].secondsRemaining() == 0)

print("[decode] candidates + confirm shapes")
let cands = """
{"candidates":[{"staffId":"S203","name":"Cassey Mudgett","onShift":true},{"staffId":"S102","name":"Matthew Mudgett"}],"windowSec":90,"ratio":"2:1","service":"W7068"}
""".data(using: .utf8)!
let c = try! JSONDecoder().decode(TwoToOneCandidatesResponse.self, from: cands)
check("candidates decode with optional onShift", c.candidates.count == 2 && c.candidates[0].onShift == true && c.candidates[1].onShift == nil && c.windowSec == 90)
let conf = """
{"visit":{"id":"V-3000","clockIn":"2:33 PM"},"visits":[{"id":"V-3000","clientId":"C673069","clockIn":"2:33 PM"}],"twoToOne":{"matched":true,"matchedClockIn":"2:33 PM","requestId":7,"fromVisitId":"V-2079","fromStaff":"Nick Mudgett"}}
""".data(using: .utf8)!
let cr = try! JSONDecoder().decode(TwoToOneConfirmResponse.self, from: conf)
check("confirm response = clock-in shape + match facts", cr.visit.id == "V-3000" && cr.visit.clockIn == "2:33 PM" && cr.twoToOne?.matched == true && cr.twoToOne?.fromStaff == "Nick Mudgett")

print("[encode] request bodies")
let enc = JSONEncoder(); enc.outputFormatting = [.sortedKeys]
let ci = String(data: try! enc.encode(ClockInRequest(lat: 1, lng: 2, accuracy: 3, address: nil, secondStaffId: "S203")), encoding: .utf8)!
check("ClockInRequest carries secondStaffId when set", ci.contains("\"secondStaffId\":\"S203\""), ci)
let ciNone = String(data: try! enc.encode(ClockInRequest(lat: 1, lng: 2, accuracy: 3, address: nil)), encoding: .utf8)!
check("…and the key is ABSENT (null) when not set — old payload for every other shift", ciNone.contains("\"secondStaffId\":null") || !ciNone.contains("secondStaffId"), ciNone)
let uv = String(data: try! enc.encode(UnscheduledVisitRequest(clientIds: ["C673069"], service: "W7068", lat: 1, lng: 2, accuracy: 3, address: nil, unlistedName: nil, startTime: nil, endTime: nil, date: nil, deliveryMode: nil, secondStaffId: "S203")), encoding: .utf8)!
check("UnscheduledVisitRequest carries secondStaffId", uv.contains("\"secondStaffId\":\"S203\""), uv)

print("\(pass) passed, \(fail) failed")
exit(fail == 0 ? 0 : 1)
