// Build 71 — decodes the REAL server payload shape (sample.json, generated by
// gen_sample.js from evv-poc's own todo-core/missed-shifts builders) with the
// REAL app structs (extracted from APIClient.swift / RequestShiftSheet.swift
// by check.sh), and exercises MissedShiftPrefill's agency-timezone parsing.
import Foundation

var pass = 0, fail = 0
func check(_ label: String, _ ok: Bool, _ extra: String = "") {
    if ok { pass += 1; print("  ✓ \(label)") } else { fail += 1; print("  ✗ \(label) \(extra)") }
}

let sampleURL = URL(fileURLWithPath: CommandLine.arguments[1])
let data = try! Data(contentsOf: sampleURL)
let resp = try! JSONDecoder().decode(MissedShiftsResponse.self, from: data)

print("[decode] GET /api/me/missed-shifts")
check("3 rows decode", resp.missedShifts.count == 3, "\(resp.missedShifts.count)")
check("reasons = the server's 5-item NOT_WORKED_REASONS", resp.reasons.count == 5 && resp.reasons.last == "Other")
check("requiredFrom = 2026-09-15 cutover", resp.requiredFrom == "2026-09-15")
check("shiftRequestMaxDays decodes", resp.shiftRequestMaxDays == 7)
let r5 = resp.missedShifts.first { $0.shiftId == 5 }!
check("shiftId is an Int (shifts.id serial)", r5.shiftId == 5)
check("key/date/start/end/clientName/serviceName carried", r5.key == "5:S1" && r5.date == "2026-09-15" && r5.start == "1:00 PM" && r5.end == "5:00 PM" && r5.clientName == "Ray V" && r5.serviceName == "IHCS")
check("service is the CODE (what the request POST sends)", r5.service == "W1726")
check("canRequest → offersRequest", r5.offersRequest && r5.requestMinDate == "2026-09-11")
check("Identifiable id = key", r5.id == "5:S1")
let r6 = resp.missedShifts.first { $0.shiftId == 6 }!
check("multi-individual shift (v0.4.508) maps clientId to the first listed individual", r6.clientId == "C1", "\(String(describing: r6.clientId))")

print("[decode] tolerance")
let minimal = """
{"missedShifts":[{"key":"9:S1","shiftId":9,"date":"2026-09-16"}],"reasons":[]}
""".data(using: .utf8)!
let m = try? JSONDecoder().decode(MissedShiftsResponse.self, from: minimal)
check("a row with only key/shiftId/date decodes (every other field optional)", m?.missedShifts.first?.shiftId == 9)
check("missing canRequest → offersRequest false", m?.missedShifts.first?.offersRequest == false)
let live = """
{"missedShifts":[],"reasons":["Staff no-show","Staff called off / sick","Shift cancelled late","Individual unavailable / declined","Other"],"requiredFrom":"2026-09-15","shiftRequestMaxDays":7}
""".data(using: .utf8)!
check("the LIVE prod response (empty list) decodes", (try? JSONDecoder().decode(MissedShiftsResponse.self, from: live))?.missedShifts.isEmpty == true)
let resolved = """
{"ok":true,"shiftId":5,"reason":"Staff no-show","comment":null}
""".data(using: .utf8)!
check("resolve response decodes", (try? JSONDecoder().decode(MissedShiftResolveResponse.self, from: resolved))?.ok == true)

print("[encode] POST bodies")
let body = try! JSONEncoder().encode(ShiftRequestBody(clientId: "C1", service: "W1726", date: "2026-09-15", startTime: "1:00 PM", endTime: "5:00 PM", reason: "forgot", shiftId: 5))
let obj = try! JSONSerialization.jsonObject(with: body) as! [String: Any]
check("shift-request body carries shiftId=5", (obj["shiftId"] as? Int) == 5)
let plain = try! JSONEncoder().encode(ShiftRequestBody(clientId: "C1", service: "W1726", date: "2026-09-15", startTime: "1:00 PM", endTime: "5:00 PM", reason: "forgot", shiftId: nil))
let pobj = try! JSONSerialization.jsonObject(with: plain) as! [String: Any]
check("ordinary request omits shiftId (nil not encoded as null → server treats as absent)", pobj["shiftId"] == nil || pobj["shiftId"] is NSNull)
let rb = try! JSONEncoder().encode(MissedShiftResolveBody(reason: "Other", comment: "car trouble"))
let robj = try! JSONSerialization.jsonObject(with: rb) as! [String: Any]
check("resolve body = {reason, comment}", (robj["reason"] as? String) == "Other" && (robj["comment"] as? String) == "car trouble")

print("[prefill] MissedShiftPrefill")
let p = MissedShiftPrefill(item: r5)!
check("prefill from a row: shiftId/clientId/code/name/date", p.shiftId == 5 && p.clientId == "C1" && p.serviceCode == "W1726" && p.serviceName == "IHCS" && p.date == "2026-09-15")
let noClient = MissedShiftItem(key: "x", shiftId: 1, staffId: nil, date: "2026-09-15", start: nil, end: nil, clientId: nil, clientName: nil, service: "W1726", serviceName: nil, lateMinutes: nil, canRequest: true, requestMinDate: nil)
check("no clientId → prefill nil (request path hidden, reason path stays)", MissedShiftPrefill(item: noClient) == nil)
let ny = TimeZone(identifier: "America/New_York")!
var cal = Calendar(identifier: .gregorian); cal.timeZone = ny
let d = MissedShiftPrefill.parse(date: "2026-09-15", time: "1:00 PM")!
let c = cal.dateComponents([.year, .month, .day, .hour, .minute], from: d)
check("parse('2026-09-15','1:00 PM') = 13:00 agency time on that day", c.year == 2026 && c.month == 9 && c.day == 15 && c.hour == 13 && c.minute == 0, "\(c)")
let d0 = MissedShiftPrefill.parse(date: "2026-09-15", time: nil)!
let c0 = cal.dateComponents([.hour, .day], from: d0)
check("parse(date only) = midnight agency time", c0.day == 15 && c0.hour == 0)
check("junk time → nil (never a crash)", MissedShiftPrefill.parse(date: "2026-09-15", time: "13h00") == nil)
// Round trip: the label the sheet sends back must equal the label it received.
let f = DateFormatter(); f.locale = Locale(identifier: "en_US_POSIX"); f.timeZone = ny; f.dateFormat = "h:mm a"
check("round-trip label 1:00 PM → Date → '1:00 PM'", f.string(from: d) == "1:00 PM")

print("[WorkItem] native == missedshift")
let wi = """
{"key":"missed-5","kind":"auto","category":"missed","title":"Missed shift — Ray V · IHCS","detail":"2026-09-15 1:00 PM–5:00 PM — no visit recorded","overdue":true,"done":false,"checkable":false,"native":"missedshift","webPath":"/visits?from=2026-09-15","shiftId":5}
""".data(using: .utf8)!
let w = try? JSONDecoder().decode(WorkItem.self, from: wi)
check("todo item decodes with shiftId=5 + native=missedshift", w?.shiftId == 5 && w?.native == "missedshift")
let wiOld = """
{"key":"doc-V-1","kind":"auto","title":"Documentation","overdue":false,"done":false,"checkable":false,"native":"documentation","visitId":"V-1"}
""".data(using: .utf8)!
check("older items without shiftId still decode", (try? JSONDecoder().decode(WorkItem.self, from: wiOld))?.visitId == "V-1")

print("\n\(pass) passed, \(fail) failed")
exit(fail == 0 ? 0 : 1)
